<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>ii.Aethra</RootNamespace>
    <AssemblyName>ii.Aethra</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Copyright>Copyright ©  2026</Copyright>
    <Title>ii.Aethra</Title>
    <Version>0.9.2.0</Version>
    <Authors>iggti</Authors>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/btigi/iiAethra</RepositoryUrl>
    <Description>C# library to facilitate editing of the 1994 CRPG The Aethra Chronicles.</Description>
    <PackageTags>Aethra Chronicles</PackageTags>
    <PackageReadmeFile>readme.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\readme.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
